### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by harshmaur** [developit/preact-tap-event-plugin#1]
Hi @developit, I think there is still one bug. 

Have a look. https://cl.ly/2e0J0W011i3v

**Comment by developit** [comment]
@harshmaur are you 100% sure you're using `0.1.1`? I was getting the `.x` issue in `0.1.0` and released a patch.

**Comment by harshmaur** [comment]
Yes, https://cl.ly/3g3p2K2Z253i

I just did `yarn add preact-tap-event-plugin`

**Comment by developit** [comment]
Just published `0.1.2`, should fix the issue. Only thing I could think of that would have caused it would be the event target changing dynamically, even though that's not supposed to happen for touch events.  It's using a closure now though, should be good.  Let me know :)

**Comment by harshmaur** [comment]
The issue is gone, but another one came up. 

`tap is not a function`

https://cl.ly/131p0N3M0I3Q

Also, If I switch to onClick, I have to click twice to make the tap happen. 

https://cl.ly/3Q412Z43182h

**Comment by linde12** [comment]
The (latest) issue that @harshmaur is getting is appearing for me as well when i'm trying it out with a MUI project.

**Comment by developit** [comment]
Alright I'll try to test this out today.

**Comment by IrregularShed** [comment]
Any success with this? I have a Preact/Material-UI project with the same `tap is not a function` error showing up when using an icon menu with 0.1.2 installed.

**Comment by developit** [comment]
Not yet - a (sourcemapped) stack trace would be useful here if you've got one @IrregularShed!

**Comment by IrregularShed** [comment]
My workspace is a little mangled (from trying to work around this!) at the moment but I'll see what I can do. [This line](https://github.com/developit/preact-tap-event-plugin/blob/master/src/index.js#L50) is where the exception is getting thrown; at this point `hasTouch` is undefined - so falsy - but `tap` is also undefined, so can't be called.

**Comment by IrregularShed** [comment]
Failing completely to get a sourcemapped version (sorry - I'm a n00b at this sort of thing) but here's what I'm getting back:
```
dev-server.js?30c5:60 [HMR] Waiting for update signal from WDS...
client?c7c8:37 [WDS] Hot Module Replacement enabled.
VM48274:9 Uncaught TypeError: tap is not a function
    at Object.attrs.(anonymous function) [as onClick] (eval at <anonymous> (http://localhost:8080/bundle.js:2830:2), <anonymous>:9:48)
    at EnhancedButton._this.handleClick (eval at <anonymous> (http://localhost:8080/bundle.js:1870:2), <anonymous>:142:21)
    at Object.attrs.(anonymous function) [as click] (eval at <anonymous> (http://localhost:8080/bundle.js:2830:2), <anonymous>:9:20)
    at HTMLSpanElement.eventProxy (eval at <anonymous> (http://localhost:8080/bundle.js:1072:2), <anonymous>:132:39)
attrs.(anonymous function) @ VM48274:9
EnhancedButton._this.handleClick @ EnhancedButton.js?839a:142
attrs.(anonymous function) @ VM48274:9
eventProxy @ index.js?14dc:91
```
This occurs when clicking on a [MenuItem](https://github.com/callemall/material-ui/blob/master/src/MenuItem/MenuItem.js) in Material UI. The Enhanced Button in the stack is [this](https://github.com/callemall/material-ui/blob/master/src/internal/EnhancedButton.js).

**Comment by IrregularShed** [comment]
Having stepped through things it looks like this is the same issue as reported in #2 😔

**Comment by developit** [comment]
Hey, at least I can reuse the repro!

**Comment by IrregularShed** [comment]
I scrapped Material UI in favour of preact-mdl (I'd fortunately not gone too far down the road with Material UI) so this is less of an issue for me personally now ☺️

**Comment by developit** [comment]
Ah yup. We did exactly the same thing at a hackathon two weeks ago, I think actually due to the same issue haha.  I really do want to solve the tap event thing, just I'm not a material-ui user (yet?).  Really really interested in [material-components-web](https://github.com/material-components/material-components-web) though since it would integrate beautifully with Preact.

**Comment by IrregularShed** [comment]
Nice, I hadn't seen material-components-web before (I've been jumping from technology to technology for so long that sometimes these things just surprise me)

**Comment by developit** [comment]
@IrregularShed yeah - I think the thing that draws me to it is that I've loved `MDL`, but it was always a little bit unwieldy because it had to do a fair bit of arbitrary DOM manipulation.  Leaving that out and pushing it into the adapter layer (a "preact-material-components") means it's a very first-class integration.  No hacks, just nice components rendering elements with nice CSS.

**Comment by FallingSnow** [comment]
> Also, If I switch to onClick, I have to click twice to make the tap happen.
https://cl.ly/3Q412Z43182h

I'm having the exact same issue.

**Comment by FallingSnow** [comment]
Don't know if this helps but I got this stack.
```javascript
Uncaught TypeError: tap is not a function
    at Object.attrs.(anonymous function) [as onClick] (http://localhost:8080/bundle.js:112645:54)
    at EnhancedButton._this.handleClick (http://localhost:8080/bundle.js:19422:21)
    at Object.attrs.(anonymous function) [as click] (http://localhost:8080/bundle.js:112645:26)
    at HTMLSpanElement.eventProxy (http://localhost:8080/bundle.js:30058:39)

attrs.(anonymous function)@ReactTransitionGroup.js:1
EnhancedButton._this.handleClick@EnhancedButton.js:142
attrs.(anonymous function)@ReactTransitionGroup.js:1
eventProxy@index.js:90
```

**Comment by FallingSnow** [comment]
Tracked it down to https://github.com/developit/preact-tap-event-plugin/blob/master/src/index.js#L50. The `tap is not a function` is simple enough to fix, but the click requiring a double tap is a bit more complicated. It looks like proxy is not called till after the element has been clicked once, therefore not hooking into the onClick function.

The double click only seems to apply to elements such as drop downs.

**Comment by developit** [comment]
Yup, thinking this is a silly error somewhere, just I don't have a perfect test for it :(

**Comment by john-hadron** [comment]
+1, same issue. `tab is not a function`, also using Material UI.

**Comment by mgoodings** [comment]
@developit I've narrowed down the onClick event issue to the TouchRipple div inside an EnhancedButton.

https://github.com/callemall/material-ui/blob/master/src/internal/TouchRipple.js#L217

If you remove the onMouseDown event binding or apply an inline style of `pointer-events: none;` to the div, you can click on any ListItem/DropDownMenu etc and the click event goes through without an issue.

The strange thing is, I can't see any code that's preventing the event from bubbling up in the onMouseDown handler.

The browser does not fire a click event at all for the first click as long as this ripple effect has a mouse down event. Some weird stuff happening here, not sure if it's an issue with Preact itself and the way it handles the browser events.

A temporary fix is the following, it will remove the ripple effects but solves the double click issue:

```
import EnhancedButton from 'material-ui/internal/EnhancedButton'
EnhancedButton.defaultProps.disableTouchRipple = true
```

**UPDATE:** After some further investigations the issue is coming from here:

https://github.com/callemall/material-ui/blob/master/src/internal/TouchRipple.js#L198

When onMouseDown is triggered, the TouchRipple component is re-rendered and the resulting Ripple effect / animation prevents the onClick event from bubbling up past the ripple.

Not sure how to solve it, it could be that the component itself is just simply not compatible with Preact because it relies on specific behavior from Synthetic events, I don't know.

**Comment by developit** [comment]
Interesting - I wonder if it's just because the element is being removed during the event handling? I could see that preventing bubbling?  Or do you think it's up the tree actually invoking `stopPropagation()`?

FWIW I think that means we could solve this by stopping propagation [here](https://github.com/developit/preact-tap-event-plugin/blob/master/src/index.js#L49)?

**Comment by mgoodings** [comment]
@developit I've created a project to demonstrate the broken components. https://github.com/mgoodings/preact-material-ui-demo

Maybe you will have more luck diagnosing the actual problem than I did.

Also regarding stopping propagation, if you add logs to that vnode onClick handler, it isn't triggered at all by any node on the first click and that's the crux of the issue.

**Comment by developit** [comment]
Cool, I'll take a look as soon as I can.
